# logstash/pipeline/kafka.conf

input {
  kafka {
    bootstrap_servers => "kafka:9092"
    topics => ["app_logs"]
    codec => json        # اگر لاگ‌ها JSON هستند
    group_id => "logstash-consumer"
    auto_offset_reset => "earliest"
  }
}

filter {
  # اگر timestamp داری parse کن
  date {
    match => ["timestamp", "ISO8601"]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "city-logs-%{+YYYY.MM.dd}"  # هر روز یک index
  }

  # برای دیباگ
  stdout { codec => rubydebug }
}
